---
#<% require 'kitchen-sync' %>
driver:
  name: vagrant

chef_versions:
- '11.12'
- '11.14'
- '11.16'
- '11'
- '12'

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[poise_test]
