---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen %>

chef_versions:
- '11.14'
- '11.16'
- '11'
- '12'

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[poise_test]
