sudo: false
cache: bundler
language: ruby
rvm:
- 2.1.4
env:
  global:
  - USE_SYSTEM_GECODE=true
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  - secure: ibzkIfnlc+qe1ki2VA9Zhg7HmjLPdlW2GMB2zxHDa2As//mUJo7m5f9oyL9+kO4zqbcBGMt51VxwjUbmDNc/XcieGKjwXRz+FBYWJwGcpuvcb3mN8iajgkrOqT07RYwrks0zVBBl4RB4UnXn3EctkTV+ond4Ee6reoYuXtPs2j0=
  - secure: jEiZqcy6E5WC1nBmfJBSLPpYOUBFdpoo7DsLrvIpKVRpOw7slb+VgIru5AzbONvVD/8CYstgqiVVoGaCP/ywWWqakOQ2thp0BqWN/OVlsuPiemAdLRMMsmekkaFUdAa5l8QUUI0YiTSpSLUXQFWZrXbiARCALGAvDBbsqF1JhgA=
before_install:
- curl -o ~/gecode.tar.gz https://poise-gecode.s3.amazonaws.com/gecode-3.7.3-ubuntu12.04-x86_64.tar.gz
- tar xzf ~/gecode.tar.gz -C ~
- rm ~/gecode.tar.gz
- bundle config build.dep_selector "--with-cflags=\"-I$HOME/gecode-3.7.3/include\"
  --with-cppflags=\"-I$HOME/gecode-3.7.3/include\" --with-ldflags=\"-L$HOME/gecode-3.7.3/lib
  -Wl,-rpath=$HOME/gecode-3.7.3/lib\""
bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3"
script:
- "./bin/rake spec"
- "./bin/rake chef:foodcritic"
- if [ "$TRAVIS_SECURE_ENV_VARS" = true ]; then openssl rsa -in test/docker/docker.pem
  -passin env:KITCHEN_DOCKER_PASS -out test/docker/docker.key; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = true ]; then wget https://get.docker.io/builds/Linux/x86_64/docker-latest
  -O docker; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = true ]; then chmod +x docker; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" = true ]; then ./bin/kitchen test -d always; fi
gemfile:
- test/gemfiles/chef-11.12.gemfile
- test/gemfiles/chef-11.14.gemfile
- test/gemfiles/chef-11.16.gemfile
- test/gemfiles/chef-11.gemfile
- test/gemfiles/chef-12.gemfile
