---
sudo: false
language: ruby
rvm:
- 2.1.4
env:
  global:
  - CFLAGS=-I~/gecode-3.7.3/include
  - LDFLAGS=-L~/gecode-3.7.3/lib
  - LD_LIBRARY_PATH=~/gecode-3.7.3/lib
  - USE_SYSTEM_GECODE=true
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  - secure: bLPw2OC3WBL9b9yW4HjPRk33JXA6enTczrwgZD6+1MZsQKUowIRMdFjcXA1mMLFESLxFETRK52YXRqDSbH0sWqrFVs8GF2a9epgEl/yPGTeIjW1QP7hLQVrCWxBfVoGij7G/0db230ErK54G1tfwyzp+XgFbcxGn+rTq6fFNxss=
before_install:
- curl -O https://poise-gecode.s3.amazonaws.com/gecode-3.7.3-ubuntu12.04-x86_64.tar.gz
- tar xzvf gecode-3.7.3-ubuntu12.04-x86_64.tar.gz
bundler_args: "--deployment --binstubs"
script:
- "./bin/foodcritic -f any ."
- openssl rsa -in .docker.pem -passin env:KITCHEN_DOCKER_PASS -out .docker.key
- wget https://get.docker.io/builds/Linux/x86_64/docker-latest -O docker
- chmod +x docker
- "./bin/kitchen test -d always"
