language: ruby
rvm:
- 2.0.0
env:
  global:
    secure: X/Ch2TUu3GtM0z9t/M1GT0sAotSe8nVl45LTZGzZhATGwQyZRPQjeXdlpnoOxFGwpf5j+tAFGqMzExEmvfv5m0acn3o5zFLru2VVxlH8E2BhsxSv7i3ThqhiwqZjSdOmoTQAu0/K/LZm0aewTuyVErw2f2V4EYxXSVzsqVlfZX4=
bundler_args: --deployment --binstubs
script:
- ./bin/foodcritic -f any .
- cp .kitchen.travis.yml .kitchen.local.yml
- ./bin/kitchen test -d always -p
