---
language: ruby
rvm:
- 1.9.3-p484
env:
  matrix:
  - CHEF_VERSION="11.6.0"
  - CHEF_VERSION="11.8.0"
  - CHEF_VERSION="11.10.0"
  - CHEF_VERSION="11.12.0"
  - CHEF_VERSION="11.12.2"
  global:
  - USE_SYSTEM_GECODE=true
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  - secure: bLPw2OC3WBL9b9yW4HjPRk33JXA6enTczrwgZD6+1MZsQKUowIRMdFjcXA1mMLFESLxFETRK52YXRqDSbH0sWqrFVs8GF2a9epgEl/yPGTeIjW1QP7hLQVrCWxBfVoGij7G/0db230ErK54G1tfwyzp+XgFbcxGn+rTq6fFNxss=
before_install:
- sudo apt-get update
- sudo apt-get install libgecode-dev
bundler_args: "--deployment --binstubs"
script:
- "./bin/foodcritic -f any ."
- ruby -e 'IO.write(".docker.pass", ENV["KITCHEN_DOCKER_PASS"])'
- openssl rsa -in .docker.pem -passin file:.docker.pass -out .docker.key
- wget https://get.docker.io/builds/Linux/x86_64/docker-latest -O docker
- chmod +x docker
- "./bin/kitchen test -d always"
