---
language: ruby
rvm:
- 1.9.3-p484
env:
  matrix:
  - KITCHEN_CHEF_VERSION="11.0.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.0.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.0.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.0.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.0.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.0.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.2.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.2.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.2.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.2.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.2.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.2.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.4.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.4.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.4.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.4.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.4.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.4.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.6.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.6.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.6.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.6.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.6.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.6.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.8.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.8.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.8.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.8.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.8.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.8.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.10.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.10.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.10.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.10.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.10.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.10.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.12.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.12.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.12.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.12.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.12.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.12.0" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  - KITCHEN_CHEF_VERSION="11.12.2" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="subcontext-block"
  - KITCHEN_CHEF_VERSION="11.12.2" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="notifying-block"
  - KITCHEN_CHEF_VERSION="11.12.2" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="include-recipe"
  - KITCHEN_CHEF_VERSION="11.12.2" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lazy-default"
  - KITCHEN_CHEF_VERSION="11.12.2" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="lwrp-polyfill"
  - KITCHEN_CHEF_VERSION="11.12.2" KITCHEN_PLATFORM="ubuntu-1204" KITCHEN_SUITE="template-content"
  global:
  - USE_SYSTEM_GECODE=true
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  - secure: bLPw2OC3WBL9b9yW4HjPRk33JXA6enTczrwgZD6+1MZsQKUowIRMdFjcXA1mMLFESLxFETRK52YXRqDSbH0sWqrFVs8GF2a9epgEl/yPGTeIjW1QP7hLQVrCWxBfVoGij7G/0db230ErK54G1tfwyzp+XgFbcxGn+rTq6fFNxss=
before_install:
- sudo apt-get update
- sudo apt-get install libgecode-dev
bundler_args: "--deployment --binstubs"
script:
- "./bin/foodcritic -f any ."
- ruby -e 'IO.write(".docker.pass", ENV["KITCHEN_DOCKER_PASS"])'
- openssl rsa -in .docker.pem -passin file:.docker.pass -out .docker.key
- wget https://get.docker.io/builds/Linux/x86_64/docker-latest -O docker
- chmod +x docker
- "./bin/kitchen test -d always $KITCHEN_SUITE-$KITCHEN_PLATFORM"
